global using DForge.DSP.Define;
global using DForge.DSP.Implement;
global using Flurl.Http;
global using Newtonsoft.Json;
global using System.Net;
global using YogoPop.Core.Extension;
global using YogoPop.Core.Injection;
global using YogoPop.Core.JsonExtend;
global using YogoPop.Core.Tool;